server:
  port: 80
 
spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrateg
        
  datasource:
    url: jdbc:mysql://localhost:3306/security?characterEncoding=utf8
    username: root
    password: Zheng1234
    
  thymeleaf:
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  
  
securityconfig:
  logoutsuccessurl: /
  permitall: /rest/**,/bbs**
  deniedpage: /deny
  urlroles: /**/new = manage,admin;
            /**/edit/** = admin;
            /**/delete/** = admin